spring:

  mail:
    host: smtp.gmail.com
    port: 587
    username: everlastings222@gmail.com
    password: iedjytqxpbxvefzv
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: web-sekolah
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true