management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: WebSekolah
    description: web sekolah
    author: team
    version: '@project.version@'
spring:
  profiles:
    active: dev

